# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20160213_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='material_type',
            name='m_type_name',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='m_download_link',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='m_title',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='subject',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='news_feed',
            name='feed',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='student_achievements',
            name='student_achievement_description',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='student_achievements',
            name='student_achievement_link',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='student_achievements',
            name='student_achievement_title',
            field=models.CharField(max_length=b'128'),
        ),
        migrations.AlterField(
            model_name='student_certifications',
            name='student_certification_URL',
            field=models.CharField(max_length=b'128'),
        ),
        migrations.AlterField(
            model_name='student_certifications',
            name='student_certification_authority',
            field=models.CharField(max_length=b'128'),
        ),
        migrations.AlterField(
            model_name='student_certifications',
            name='student_certification_date',
            field=models.CharField(max_length=b'128'),
        ),
        migrations.AlterField(
            model_name='student_certifications',
            name='student_certification_license_number',
            field=models.CharField(max_length=b'128'),
        ),
        migrations.AlterField(
            model_name='student_certifications',
            name='student_certification_name',
            field=models.CharField(max_length=b'128'),
        ),
        migrations.AlterField(
            model_name='student_projects',
            name='student_project_URL',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='student_projects',
            name='student_project_description',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='student_projects',
            name='student_project_end_year_date',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='student_projects',
            name='student_project_name',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='student_projects',
            name='student_project_start_year_date',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='work_publish',
            name='work_desc',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='work_publish',
            name='work_name',
            field=models.CharField(max_length=b'255'),
        ),
        migrations.AlterField(
            model_name='work_publish',
            name='work_sub',
            field=models.CharField(max_length=b'255'),
        ),
    ]
